allow for user identity creation
givtnl/Givt.App.Flutter pull request #19
Opened 2022-11-07 11:21 UTC by Daniela510

>> the current first use flow introduces the sign up page after a donation was completed. In order to complete a donation we generate and store user data like a guid. So most users will type in their email and backend will confirm this user does not exist, however locally most users will have a guid that was generated for the donation. Therefore most likely case in sign up is: email = doesNotExist (in db), local.guid.exists = true. This might change depending on how donations will occur the 2.0 backend, and what type of users will exist in the 2.0 data model.
>> The log in functionality works, the access and bearer tokens are returned, but is not implemented as app state because there is no usecase for it yet, judged it outside scope
>> forgot password functionality does not exist, judged it outside scope of story as well.

2022-11-07 13:00 UTC, phalox requested changes
More to come. Just finished first files

2022-11-07 13:02 UTC, Daniela510 commented on lib/core/widgets/navigation/appbar_bottom.dart
> +                              // this should check whether user is logged in
yes its for future reference the navbar functionality is outside of scope, but i used it so i could try out the user identity feature without having to make a donation every time(our current flow)

2022-11-07 14:00 UTC, phalox commented on lib/core/widgets/navigation/appbar_bottom.dart
> +                              // this should check whether user is logged in
I'll leave it here, so you can resolve you when you're done with testing ?

2022-11-07 14:06 UTC, phalox commented on lib/features/user_identity_creation/controller/sign_up.dart
> +    if (emailStatus.contains('dashboard') || emailStatus.contains('temp')) {
woah, what does that API call return ?? shouldn't we do these checks in the checkEmailExists() call ? it feels like we're exposing internal implementation too much, which we can hide in our API Service.

2022-11-07 14:07 UTC, phalox commented on lib/features/user_identity_creation/controller/sign_up.dart
> +    if (emailStatus.contains('dashboard') || emailStatus.contains('temp')) {
Once we do that, I think we can change the name to emailExists which is more descriptive.

2022-11-07 14:08 UTC, phalox commented on lib/features/user_identity_creation/controller/sign_up.dart
> +        ////////////  HAPPY PATH in current giving flow ////////////
you don't need an else, you can just abort when ending the if(). Like this you prevent more indentation / conditional paths.

2022-11-07 14:11 UTC, phalox commented on lib/features/user_identity_creation/controller/sign_up.dart
> +        final res = await _userService.postRegisteredUser(
I'd create a User object and set these values inside, then pass that to postRegisteredUser.

what does 'post' mean here? it's not a very descriptive verb? from the service it looks more like registerUser(), but it seems it's using a temp user account? so then upgradeTempUserToFull ? Something like it?

2022-11-07 14:12 UTC, phalox commented on lib/features/user_identity_creation/page/login.dart
> +  bool _passwordVisible = true;
I guess this should be set to false by default?

2022-11-07 14:14 UTC, phalox commented on lib/features/user_identity_creation/page/login.dart
> +                    return 'Password must be at least 7 characters long';
We for sure also have a check on max length. The hashed password in the db is max 100 chars, but a salt is added. we should align with the check in the backend. @AlexGivt can probably find this fast :)

2022-11-07 14:16 UTC, phalox commented on lib/features/user_identity_creation/page/login.dart
> +                          LoginController().onLogin(
I'm not sure if this makes any sense, but shouldn't this be the LoginService ?

and onLogin would typically be the name of an event handler, but now you're calling it, so login() makes more sense to me....)

2022-11-07 14:17 UTC, phalox commented on lib/features/user_identity_creation/page/login.dart
> +                            toggleLoader,
Last thing I'm not sure about: Passing this toggleLoader everwywhere clutters the code, but i have no idea how to make it better?

2022-11-07 14:18 UTC, phalox commented on lib/features/user_identity_creation/page/sign_up.dart
> +                  ),
same 10 lines below: onSignup seems like a wrong name. I think should be Signup ?

2022-11-07 14:20 UTC, phalox commented on lib/models/grant_request.dart
> +import 'package:json_annotation/json_annotation.dart';
I don't know the API well enough, but I think this stuff should not be internally exposed as a model.... At least not now. API should hide it all.

2022-11-07 14:21 UTC, phalox commented on lib/services/api_service.dart
> +  Future<dynamic> loginLocal(Map data) async {
why not just login()?

2022-11-07 14:21 UTC, phalox commented on lib/services/api_service.dart
> +  Future<dynamic> loginLocal(Map data) async {
Here I would expect Username and Password, not a map with data

2022-11-07 14:23 UTC, phalox commented on lib/services/user_service.dart
> +    print(
Todo remove :-)

2022-11-07 14:24 UTC, phalox commented on lib/services/user_service.dart
> +        await createTempUser(ctx, firstName, lastName, null, email, password);
This function mostly looks the same as the one below. I think you should make modifications so you only need the one

2022-11-07 15:44 UTC, Daniela510 commented on lib/features/user_identity_creation/page/login.dart
> +                    return 'Password must be at least 7 characters long';
Alex was the source for these validation parameters, but doesn't hurt to double check

2022-11-07 15:45 UTC, Daniela510 commented on lib/features/user_identity_creation/page/login.dart
> +                            toggleLoader,
no idea either, but something to think about. It needs to update the state so it cant be defined in the controller

2022-11-07 15:45 UTC, Daniela510 commented on lib/features/user_identity_creation/page/sign_up.dart
> +                  ),
yup

2022-11-07 15:51 UTC, Daniela510 commented on lib/services/api_service.dart
> +  Future<dynamic> loginLocal(Map data) async {
This is just the api service that calls the endpoint, it needs a map to transfer data as x-www-form-urlencoded. Username and password are passed to the user service, that then creates a map, calls the endpoint with said map, and stores the access_token.

2022-11-08 08:44 UTC, AlexGivt commented on lib/features/user_identity_creation/controller/login.dart
> +      final response = await APIService().loginLocal(data);
Agree that userService should be abstracted from the API, in the future we may use an external Authentication service (not in our API).

2022-11-08 08:45 UTC, AlexGivt commented on lib/features/user_identity_creation/controller/login.dart
> +      final response = await APIService().loginLocal(data);
Passing username/password is one way of authentication, there could be other authentication data. So passing in a structure of some kind with authentication data for me is a good option, no need to split into username/password. But the name "data" is a bit too generic here (nitpicking ;-) )

2022-11-08 08:48 UTC, AlexGivt commented on lib/features/user_identity_creation/controller/sign_up.dart
> +    if (emailStatus.contains('dashboard') || emailStatus.contains('temp')) {
I think it is better to see the "thing" returned from the authentication service, as an identity. An identity carries certain credentials, so `if (identity.hasCredential(CredentialItems.dashboard) || identity.hasCredential(CredentialItems.temp)) ...`

2022-11-08 08:50 UTC, AlexGivt commented on lib/features/user_identity_creation/controller/sign_up.dart
> +        final res = await _userService.postRegisteredUser(
Agree that the methods on an object should not be simply the HTTP verbs. So rename to something like "create" or "update"

2022-11-08 08:52 UTC, AlexGivt commented on lib/services/api_service.dart
> +  Future<dynamic> loginLocal(Map data) async {
Why would a api service do a local login?

2022-11-08 08:54 UTC, AlexGivt commented on lib/features/user_identity_creation/page/login.dart
> +                    return 'Password must be at least 7 characters long';
the API configures IdentiyFramework with these parameters:
`PasswordOptions { RequireDigit = true, RequiredLength = 7, RequireUppercase = true, RequireNonAlphanumeric = false, RequireLowercase = false };` so it seems correct. Though strangely enough I managed to create a password without a capital through some dashboard....

2022-11-08 08:56 UTC, AlexGivt commented on lib/features/user_identity_creation/page/login.dart
> +                            toggleLoader,
Make toggleLoader a Singleton? @Daniela510

2022-11-08 09:35 UTC, Daniela510 commented on lib/services/api_service.dart
> +  Future<dynamic> loginLocal(Map data) async {
bad naming I guess, its logging in a user, then in future this will update the (local) state

2022-11-08 09:36 UTC, Daniela510 commented on lib/features/user_identity_creation/page/login.dart
> +                    return 'Password must be at least 7 characters long';
So the conclusion is: no max length check in the back end. Do we want a max length check in the frontend anyway?

2022-11-08 09:55 UTC, Daniela510 commented on lib/features/user_identity_creation/controller/login.dart
> +      final response = await APIService().loginLocal(data);
Yes the API call has already been moved to the user service yesterday, and I kept the data passed as a map.

2022-11-08 09:58 UTC, Daniela510 commented on lib/features/user_identity_creation/controller/sign_up.dart
> +    if (emailStatus.contains('dashboard') || emailStatus.contains('temp')) {
I changed it to emailExists because that is the only check I am really implementing, user identity is more descriptive but we are not atually using these statuses. So in the current code I removed mentions of temp or dashboard.

2022-11-08 10:06 UTC, Daniela510 commented on lib/features/user_identity_creation/controller/sign_up.dart
> +        final res = await _userService.postRegisteredUser(
yes, this comment is marked 'outdated' because the code has already been changed, that function is now _userService.updateUserIdentity

2022-11-08 10:49 UTC, Daniela510 commented on lib/features/user_identity_creation/page/login.dart
> +                            toggleLoader,
I cannot register as a singleton since it's a state setter for the parent widget. But I think it should be resolved by implementing better state management. I researched and some solutions came up by implementing the bloc pattern. Once our architecture/state management is decided I will implement this. I put it as a subtask on STYL-436 ' Apply architecture pattern to current app code '

2022-11-08 10:51 UTC, AlexGivt commented on lib/services/api_service.dart
> +  Future<dynamic> loginLocal(Map data) async {
Logging in and updating local state are different things. If the (local) state is inside one service (userService, for instance), that is OK as that local state is how the service is implemented, and the local state should be completely hidden from the rest of the app, but otherwise they should be separated and managed somewhere else

2022-11-08 11:04 UTC, AlexGivt approved these changes

2022-11-08 11:22 UTC, Daniela510 commented on lib/core/widgets/navigation/appbar_bottom.dart
> +                              // this should check whether user is logged in
I think i will leave it in for now because its useful for now, but resolve to merge

2022-11-08 11:24 UTC, Daniela510 commented on lib/features/user_identity_creation/page/login.dart
> +  bool _passwordVisible = true;
confusing naming, its changed

2022-11-08 11:26 UTC, Daniela510 commented on lib/features/user_identity_creation/page/login.dart
> +                    return 'Password must be at least 7 characters long';
done

2022-11-09 08:59 UTC, phalox commented on lib/services/api_service.dart
> +      body: loginCredentials,
Does this still work now? I think above you removed the jsonEncode in the calling function. So shouldn't it be here?

2022-11-09 08:59 UTC, phalox commented on lib/services/user_service.dart
> +    final encodedUser = jsonEncode(regUser);
so this should move into the apiservice. but let's make that a separate story

2022-11-09 09:01 UTC, phalox commented on lib/services/user_service.dart
> +    final encodedUser = jsonEncode(regUser);
Done: https://nfcollect.atlassian.net/browse/STYL-465

2022-11-09 09:02 UTC, phalox commented on lib/services/user_service.dart
> +    return decodedRes['access_token'];
I think you'll need to rework this in the future as well. the UserService should keep the access token inside the service and not expose it to the rest of the app which shouldn't need it. Do you want to fix that here or do it in the future?

2022-11-09 09:07 UTC, Daniela510 commented on lib/services/api_service.dart
> +      body: loginCredentials,
this specific call never sent json, it sends a map because then flutter/the http package encodes that as xxx-form-urlencoded

2022-11-09 09:10 UTC, Daniela510 commented on lib/services/user_service.dart
> +    return decodedRes['access_token'];
I am not using the access token so I will just remove it now, keep in mind for later

2022-11-09 09:20 UTC, phalox approved these changes
looks good to me

2022-11-09 09:20 UTC, merged